# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/seq2label.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/seq2label.proto',
  package='seq2species.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x16protos/seq2label.proto\x12\x12seq2species.protos\"\xec\x01\n\x14Seq2LabelDatasetInfo\x12\x42\n\x06labels\x18\x03 \x03(\x0b\x32\x32.seq2species.protos.Seq2LabelDatasetInfo.LabelInfo\x12\x13\n\x0bread_length\x18\x04 \x01(\x05\x12\x13\n\x0bread_stride\x18\x07 \x01(\x05\x12\x14\n\x0cnum_examples\x18\x05 \x01(\x03\x12\x14\n\x0c\x64\x61taset_path\x18\x06 \x01(\t\x1a:\n\tLabelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\x12\x0f\n\x07weights\x18\x03 \x03(\x02\"\xae\x01\n\x12Seq2LabelModelInfo\x12\x16\n\x0ehparams_string\x18\x01 \x01(\t\x12\x12\n\nmodel_type\x18\x02 \x01(\t\x12\x0f\n\x07targets\x18\x03 \x03(\t\x12\x13\n\x0bnum_filters\x18\x04 \x01(\x05\x12\x12\n\nbatch_size\x18\x05 \x01(\x05\x12\x15\n\rmetadata_path\x18\x06 \x01(\t\x12\x1b\n\x13training_noise_rate\x18\x07 \x01(\x02\"\xea\x01\n\x1bSeq2LabelExperimentMeasures\x12\x17\n\x0f\x63heckpoint_path\x18\x01 \x01(\t\x12\r\n\x05steps\x18\x02 \x01(\x03\x12\x11\n\twall_time\x18\x03 \x01(\x02\x12\x1d\n\x15\x65xperiment_infeasible\x18\x04 \x01(\x08\x12I\n\x08measures\x18\x05 \x03(\x0b\x32\x37.seq2species.protos.Seq2LabelExperimentMeasures.Measure\x1a&\n\x07Measure\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEQ2LABELDATASETINFO_LABELINFO = _descriptor.Descriptor(
  name='LabelInfo',
  full_name='seq2species.protos.Seq2LabelDatasetInfo.LabelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='seq2species.protos.Seq2LabelDatasetInfo.LabelInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='seq2species.protos.Seq2LabelDatasetInfo.LabelInfo.values', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weights', full_name='seq2species.protos.Seq2LabelDatasetInfo.LabelInfo.weights', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=283,
)

_SEQ2LABELDATASETINFO = _descriptor.Descriptor(
  name='Seq2LabelDatasetInfo',
  full_name='seq2species.protos.Seq2LabelDatasetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='seq2species.protos.Seq2LabelDatasetInfo.labels', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_length', full_name='seq2species.protos.Seq2LabelDatasetInfo.read_length', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_stride', full_name='seq2species.protos.Seq2LabelDatasetInfo.read_stride', index=2,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_examples', full_name='seq2species.protos.Seq2LabelDatasetInfo.num_examples', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataset_path', full_name='seq2species.protos.Seq2LabelDatasetInfo.dataset_path', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SEQ2LABELDATASETINFO_LABELINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=283,
)


_SEQ2LABELMODELINFO = _descriptor.Descriptor(
  name='Seq2LabelModelInfo',
  full_name='seq2species.protos.Seq2LabelModelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hparams_string', full_name='seq2species.protos.Seq2LabelModelInfo.hparams_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='seq2species.protos.Seq2LabelModelInfo.model_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targets', full_name='seq2species.protos.Seq2LabelModelInfo.targets', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_filters', full_name='seq2species.protos.Seq2LabelModelInfo.num_filters', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='seq2species.protos.Seq2LabelModelInfo.batch_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata_path', full_name='seq2species.protos.Seq2LabelModelInfo.metadata_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='training_noise_rate', full_name='seq2species.protos.Seq2LabelModelInfo.training_noise_rate', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=460,
)


_SEQ2LABELEXPERIMENTMEASURES_MEASURE = _descriptor.Descriptor(
  name='Measure',
  full_name='seq2species.protos.Seq2LabelExperimentMeasures.Measure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='seq2species.protos.Seq2LabelExperimentMeasures.Measure.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='seq2species.protos.Seq2LabelExperimentMeasures.Measure.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=659,
  serialized_end=697,
)

_SEQ2LABELEXPERIMENTMEASURES = _descriptor.Descriptor(
  name='Seq2LabelExperimentMeasures',
  full_name='seq2species.protos.Seq2LabelExperimentMeasures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='checkpoint_path', full_name='seq2species.protos.Seq2LabelExperimentMeasures.checkpoint_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steps', full_name='seq2species.protos.Seq2LabelExperimentMeasures.steps', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wall_time', full_name='seq2species.protos.Seq2LabelExperimentMeasures.wall_time', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experiment_infeasible', full_name='seq2species.protos.Seq2LabelExperimentMeasures.experiment_infeasible', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measures', full_name='seq2species.protos.Seq2LabelExperimentMeasures.measures', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SEQ2LABELEXPERIMENTMEASURES_MEASURE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=697,
)

_SEQ2LABELDATASETINFO_LABELINFO.containing_type = _SEQ2LABELDATASETINFO
_SEQ2LABELDATASETINFO.fields_by_name['labels'].message_type = _SEQ2LABELDATASETINFO_LABELINFO
_SEQ2LABELEXPERIMENTMEASURES_MEASURE.containing_type = _SEQ2LABELEXPERIMENTMEASURES
_SEQ2LABELEXPERIMENTMEASURES.fields_by_name['measures'].message_type = _SEQ2LABELEXPERIMENTMEASURES_MEASURE
DESCRIPTOR.message_types_by_name['Seq2LabelDatasetInfo'] = _SEQ2LABELDATASETINFO
DESCRIPTOR.message_types_by_name['Seq2LabelModelInfo'] = _SEQ2LABELMODELINFO
DESCRIPTOR.message_types_by_name['Seq2LabelExperimentMeasures'] = _SEQ2LABELEXPERIMENTMEASURES

Seq2LabelDatasetInfo = _reflection.GeneratedProtocolMessageType('Seq2LabelDatasetInfo', (_message.Message,), dict(

  LabelInfo = _reflection.GeneratedProtocolMessageType('LabelInfo', (_message.Message,), dict(
    DESCRIPTOR = _SEQ2LABELDATASETINFO_LABELINFO,
    __module__ = 'protos.seq2label_pb2'
    # @@protoc_insertion_point(class_scope:seq2species.protos.Seq2LabelDatasetInfo.LabelInfo)
    ))
  ,
  DESCRIPTOR = _SEQ2LABELDATASETINFO,
  __module__ = 'protos.seq2label_pb2'
  # @@protoc_insertion_point(class_scope:seq2species.protos.Seq2LabelDatasetInfo)
  ))
_sym_db.RegisterMessage(Seq2LabelDatasetInfo)
_sym_db.RegisterMessage(Seq2LabelDatasetInfo.LabelInfo)

Seq2LabelModelInfo = _reflection.GeneratedProtocolMessageType('Seq2LabelModelInfo', (_message.Message,), dict(
  DESCRIPTOR = _SEQ2LABELMODELINFO,
  __module__ = 'protos.seq2label_pb2'
  # @@protoc_insertion_point(class_scope:seq2species.protos.Seq2LabelModelInfo)
  ))
_sym_db.RegisterMessage(Seq2LabelModelInfo)

Seq2LabelExperimentMeasures = _reflection.GeneratedProtocolMessageType('Seq2LabelExperimentMeasures', (_message.Message,), dict(

  Measure = _reflection.GeneratedProtocolMessageType('Measure', (_message.Message,), dict(
    DESCRIPTOR = _SEQ2LABELEXPERIMENTMEASURES_MEASURE,
    __module__ = 'protos.seq2label_pb2'
    # @@protoc_insertion_point(class_scope:seq2species.protos.Seq2LabelExperimentMeasures.Measure)
    ))
  ,
  DESCRIPTOR = _SEQ2LABELEXPERIMENTMEASURES,
  __module__ = 'protos.seq2label_pb2'
  # @@protoc_insertion_point(class_scope:seq2species.protos.Seq2LabelExperimentMeasures)
  ))
_sym_db.RegisterMessage(Seq2LabelExperimentMeasures)
_sym_db.RegisterMessage(Seq2LabelExperimentMeasures.Measure)


# @@protoc_insertion_point(module_scope)
